### ISSUE TITLE
Thanks for your work!

### ISSUE THREAD

**Issue by cedrozor** [stchan/PdfScribe#1]
Hi Sherman,

I would like to thank you for your pdf scribe printer; I use it for my own project https://github.com/cedrozor/myrtille with great success! :)

I needed a PDF virtual printer for Myrtille and didn't wanted to rely on PDFCreator (I used it long time ago, but it now comes with some adware) or any commercial printer.

Yours is simple, with nice exception handling and efficient :)

Regards,
Cedric

**Comment by stchan** [comment]
hey Cedric -
Thank you for the kind words! I am very glad to hear you found my project
useful - sometimes I wonder if anyone browses into my little corner of the
world. I'm also glad to find out about Myrtille - it looks like something I
could use.

Cheers,
-STC
