### ISSUE TITLE
Exception in Windows 10

### ISSUE THREAD

**Issue by itc-arsalan** [stchan/PdfScribe#10]
Hi,

I am using your source code from version 1.0.5 this time but I still get an exception on line 172 in Program.cs

```
using (SaveFileDialog pdfFilenameDialog = new SaveFileDialog())
                        {
                            pdfFilenameDialog.AddExtension = true;
                            pdfFilenameDialog.AutoUpgradeEnabled = true;
                            pdfFilenameDialog.CheckPathExists = true;
                            pdfFilenameDialog.Filter = "pdf files (*.pdf)|*.pdf";
                            pdfFilenameDialog.ShowHelp = false;
                            pdfFilenameDialog.Title = "PDF Scribe - Set output filename";
                            pdfFilenameDialog.ValidateNames = true;
                            if (pdfFilenameDialog.ShowDialog(dialogOwner) == DialogResult.OK)
```
The stack trace is 

Exception Info: System.InvalidOperationException
   at System.Windows.Forms.CommonDialog.ShowDialog(System.Windows.Forms.IWin32Window)
   at PdfScribe.Program.GetPdfOutputFilename(System.String ByRef)
   at PdfScribe.Program.Main(System.String[])

There is no error in the UI but I never receive a prompt to the save dialog to save the pdf. This is with both the installer provided in the release and by building the project myself. In Windows 7 I get the prompt to the save dialog.

**Comment by itc-arsalan** [comment]
Seems like a kernel problem when calling ShowDialog. Restarting the OS and trying again seems to have resolved it.

**Comment by stchan** [comment]
did there happen to be windows updates waiting to be installed?

**Comment by itc-arsalan** [comment]
I have no pending updates. Last update was installed Jan 18th.
