### ISSUE TITLE
NOT A ISSUE...Get number of copies(and other settings) user select while print. 

### ISSUE THREAD

**Issue by trilok54660** [stchan/PdfScribe#11]
First of all Great Project.... Thanks..
I want to get number of copies and other settings when user did print... like 
Oriantation, number of copies, number page he selected

**Comment by stchan** [comment]
You're probably going to have to implement some custom print UI code to do this - there's nothing in the current code that can supply this info.

**Comment by trilok54660** [comment]
Can you please guide me with some code... :)

**Comment by stchan** [comment]
You'll have to look at the Windows Driver Kit for sample code - you can start with some of the documentation [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/com-interfaces-for-ui-plug-ins). Some of the samples are on [github itself](https://github.com/Microsoft/Windows-driver-samples/tree/master/print). Make sure you're looking at documentation/samples for V3 printer drivers.
