### ISSUE TITLE
NOT A ISSUE...Get page range selected by user select while print.

### ISSUE THREAD

**Issue by trilok54660** [stchan/PdfScribe#12]
First of all Great Project.... Thanks..
I want to get page range when user did print... like number page he selected... please help

**Comment by stchan** [comment]
This is just like issue #11 - you'll have to implement this through some custom ui code - see my response to #11 for the links to reference material. I haven't looked into this as it's not on my to-do list.

**Comment by trilok54660** [comment]
but sir i am able to get those number of copies from devmode but page range is not there. anyother way please let me know. please it is humble request from me

**Comment by stchan** [comment]
This is not something I can put any time into. You may want to look into entering an issue on your fork of this project and marking it with "Help Wanted", or asking for help on developer's forums elsewhere.
