### ISSUE TITLE
Couldn't use environment variable in output filename

### ISSUE THREAD

**Issue by qwqVictor** [stchan/PdfScribe#13]
The `PdfScribe.exe.config` is that:
```xml
<?xml version="1.0"?>
<configuration>
  <configSections>
    <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
      <section name="PdfScribe.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    </sectionGroup>
  </configSections>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/>
  </startup>
  <system.diagnostics>
    <trace autoflush="true" />
    <sources>
      <source name="PdfScribe"
               switchName="PdfScribeAll" >
        <listeners>
          <add name="textwriterListener"
              type="System.Diagnostics.TextWriterTraceListener"
              initializeData="PdfScribe_trace.log"
              traceOutputOptions="DateTime" />
          <remove name="Default" />
          <clear /> <!-- Remove the <clear /> element to turn on tracing output -->
        </listeners>
      </source>
    </sources>
    <switches>
      <add name="PdfScribeAll" value="Verbose"/>
    </switches>
  </system.diagnostics>
  <applicationSettings>
    <PdfScribe.Properties.Settings>
        <setting name="OutputFile" serializeAs="String">
            <value>C:\Temp\TEMP_%RAND%.PDF</value>
        </setting>
        <setting name="AskUserForOutputFilename" serializeAs="String">
            <value>False</value>
        </setting>
        <setting name="OpenAfterCreating" serializeAs="String">
            <value>True</value>
        </setting>
    </PdfScribe.Properties.Settings>
  </applicationSettings>
</configuration>
```
The environment variable `RAND` is my custom system environment variable. It does not contain any illegal characters, but PdfScribe couldn't save the PDF and threw out an error called -100.

**Comment by stchan** [comment]
bug confirmed

**Comment by qwqVictor** [comment]
Looking forward to a new release with this bug fixed.
In addition, why not add an option for using random filename? Or define a placeholder such as `:RANDOM:` which means random string? This could be helpful in order not to overwrite the file.

**Comment by stchan** [comment]
Generally I want to keep PdfScribe a basic, reliable tool - I've been slow
to add features to avoid expanding its scope without deliberating over why
particular changes would be desirable. Do check out some of the forks
people have created (I like to believe the simplicity of the project
encourages people to customize it for their needs - there's not a lot of
code to digest) - while I haven't browsed them for a while, there's at
least one that has an option to run a batch file after the PDF is created -
maybe you could use that to rename files randomly. Or, maybe create your
own fork that does exactly what you need.

**Comment by qwqVictor** [comment]
Thank you the feature that I can run a batch file after the PDF is created is a breakthrough feature. Looking forward to it!

**Comment by stchan** [comment]
I think you may have misunderstood - I meant one of the forks has this
feature - I'm not planning on adding it.

Look here:
https://github.com/matthewgregg/PdfScribe

**Comment by qwqVictor** [comment]
OK, Thank you.

**Comment by stchan** [comment]
see release v1.0.7
