### ISSUE TITLE
Not able to print from Photos

### ISSUE THREAD

**Issue by trilok54660** [stchan/PdfScribe#14]
Driver not working when i try to print from window's photos
i am trying from below window's native photos app
![image](https://user-images.githubusercontent.com/15190758/58646230-972dd200-8322-11e9-999b-0a8cec7b0367.png)

**Comment by stchan** [comment]
It looks like UWP apps have issues when the spooler isn't used. I found this also happens with other Windows Store apps (like OneNote). Print jobs from UWP apps also seem to just disappear when I set my physical printer (an Epson Inkjet) to "Print directly to Printer".

Changing PdfScribe's setting to "Spool print documents so program finishes printing faster" seems to fix this (open Printer Properties, then click the "Advanced" tab).

**Comment by trilok54660** [comment]
Thank you that resolved my issue. but is it possible to change that settings by installer or may be in .ppd file

**Comment by stchan** [comment]
see release v1.0.7
