### ISSUE TITLE
Understanding the PdfScribe Project

### ISSUE THREAD

**Issue by shashankSkydale** [stchan/PdfScribe#19]
Hi,
Please walk me through or give brief overview of different projects as part of PdfScribe and how Ghostscript and Redmon in conjunction with PdfScribe works to deliver pdf files.

**Comment by stchan** [comment]
While I'm willing to answer questions about the code or address bugs, you're just going to have to do your own homework - I don't have the time or inclination to to give personalized lessons. As I mentioned in #18, googling "Redmon Ghostscript PDF Printer" is a great place to start.
