### ISSUE TITLE
Ghostscript Error 100

### ISSUE THREAD

**Issue by trilok54660** [stchan/PdfScribe#25]
![picturemessage_moaloifw pus](https://user-images.githubusercontent.com/15190758/63741579-50b12a80-c8b3-11e9-951c-c54cdcb3e4d1.png)
This is an error occurring when I am trying to print from adobe reader. This error only occurs when I am trying to print some specific document(I can't upload that document). Please help 

Thank you

**Comment by trilok54660** [comment]
I just got to know that when I open specific pdf that is secure when I open from adobe reader that is open in a secure mode. and when I open that same pdf in chrome that is unsecure. so my question is any parameter we can pass to ghostscript to remove secure mode and able to process.

**Comment by stchan** [comment]
-100 is the generic Ghostscript "fatal error". Not particularly helpful, I know, but whenever I've run into it, some bad postscript input was usually involved.

I'm not surprised at all that Acrobat Reader is outputting some PS that is causing trouble (you could turn on Redmon debugging/logging and see what PS command(s) is the problem) - Adobe software is very meticulous about abiding by PDF security. Just as you've found, the traditional work around is to simply use third party software which ignores security to open the PDF.

If you already have the PDF, you can just use Ghostscript to work with it directly - there's no need to print it to PDFScribe - see this superuser question:

https://superuser.com/questions/1142426/take-protected-secure-pdf-and-save-as-editable-normal-pdf

**Comment by stchan** [comment]
closed due to inactivity

**Comment by stchan** [comment]
See [Prerelease v1.2.1](https://github.com/stchan/PdfScribe/releases/tag/v1.2.1_prerelease) for a potential fix
