### ISSUE TITLE
bug with filename containing unicode/utf8 letters

### ISSUE THREAD

**Issue by SuperUserNameMan** [stchan/PdfScribe#26]
Hello,
Very helpful project. Thanks a lot for developing and sharing it.

**Context :**
- Windows 8.1 64bits (french version)
- PdfScribe v1.0.7 downloaded from your github releases.

**I found this bug** :
- When the filename of the printed pdf contains unicode/utf8 letters, the saved filename might ends-up truncated.

**How to replicate :**
- Save a printed pdf as : ``facture_échantillons.pdf``

**Observed result :**
- The pdf will be saved as : ``facture_฀``

**Comment by stchan** [comment]
looks like including a newer ghostscript dll (v9.27) has fixed this. See release v1.0.8

**Comment by SuperUserNameMan** [comment]
@stchan : thanks ! it works perfectly with ``test_âäà_êëéè€_ïî_ôö_ûüù_ÿ_ñ.pdf``.

Just for curiosity, I tried with ``中国要求重启谈判.pdf`` and with ``призывает.pdf``, and I got this error in a dialog box : "PDF Scribe : There was a PDF generation error. Ghostscript error code -100."

**Comment by stchan** [comment]
I'm guessing there's some issue with how parameters need to be encoded for Ghostscript when non-latin alphabets are involved. There was an [issue filed](https://github.com/mephraim/ghostscriptsharp/issues/14) for GhostscriptSharp (PdfScribe uses code from a very old version of Matthew Ephraim's wrapper) regarding Japanese characters, though I'm not sure if it's related.

Addressing this will have to take a backseat to #17 though, and that has to wait until I've got more time to work on PdfScribe.

**Comment by Zhuangkh** [comment]
https://github.com/stchan/PdfScribe/pull/40 

I submitted a small fix for this problem, call the [set_arg_encoding](https://www.ghostscript.com/doc/API.htm#set_arg_encoding) before InitAPI.

**Comment by stchan** [comment]
Changes merged, included in latest release (1.1.2) - thanks for the fix - closing.
