### ISSUE TITLE
Choosing custom paper size

### ISSUE THREAD

**Issue by aacred** [stchan/PdfScribe#27]
`String[] ghostScriptArguments = 
                    {
                        "-dBATCH",
                        "-dNOPAUSE",
                        "-dSAFER",
                        "-sDEVICE=pdfwrite",
                        String.Format("-sOutputFile={0}", outputFilename),
                        standardInputFilename,
                        "-c",
                        @"[/Creator(PdfScribe 1.0.7 (PSCRIPT5)) /DOCINFO pdfmark",
                        "-f"
                    };`

As I understand the ability to set custom papersize is to use ghostscript arguments _-dDEVICEWIDTHPOINTS=w -dDEVICEHEIGHTPOINTS=h_ in that piece of code?

**Comment by stchan** [comment]
Despite having it on the to do list for years, I haven't looked into custom papersize parameters, so I don't know which particular ones to use - however, that is the line of code to change if you want to feed additional/different parameters to Ghostscript.

**Comment by stchan** [comment]
closed due to inactivity
