### ISSUE TITLE
any method to get the filename of printed file

### ISSUE THREAD

**Issue by qiyadeng** [stchan/PdfScribe#29]
I want use printed file name to map ,which file was converted.
Is there anything method to get it ?
Thank you.

**Comment by stchan** [comment]
No, it's not retained - you'll have to make your own mods if this is something you want.

**Comment by qiyadeng** [comment]
Thank you.
I transfer document name from redom, use %d parameter ,transfers  to PdfScribe main method.
[printer setting- port setting]
REDMON_DOCNAME is the name of the print job (e.g. "Printer Test Page"). %d in the program arguments will be replaced by the name of print job.
Detail is here http://www.ghostgum.com.au/software/redmon19.htm

**Comment by stchan** [comment]
Thanks for the follow-up. Glad to see you found a solution that works for you.

**Comment by stchan** [comment]
closing because qiyadeng found own solution
