### ISSUE TITLE
Can we forward the print job to print queue without convert to PDF

### ISSUE THREAD

**Issue by kisskumam** [stchan/PdfScribe#31]
Hi,

Really appreciated for what you have provided here with this awesome project. I have a question regarding to the print job in program.cs file. In my project, I need to handle for some case that does not required to convert to PDF. Therefore, the inputted document should directly forward to printer. Is it possible here to do so in this project?

Thank you so much!

**Comment by stchan** [comment]
Unfortunately in this case, PdfScribe is at the end of the pipeline - what it's receiving on its standard input is the postscript output from the PS driver (ie whatever PdfScribe receives has already been sent to the print queue). If it's just a simple case where some documents are destined to be hardcopy immediately, it might be simpler to just have the user print to a real physical printer in those situations.

**Comment by kisskumam** [comment]
Thank you for the answer

**Comment by Sulecio** [comment]
You could modify it so that at the end of the output you open it with the reader
of sumatrapdf which by command line you can redirect to a specific printer useful for remote desktop
