### ISSUE TITLE
Pages are rotated

### ISSUE THREAD

**Issue by maitreyamaity** [stchan/PdfScribe#32]
Hi,

Thanks for such a helpful project.
I would like to inform about an issue. 

Scenario 1:  The input PDF file with default page size i.e. A4. The generated output  PDF file also contains identical pages i.e. A4.

Scenario 2: The input PDF file with custom page size i.e. epos bill receipt (height-width ratio is quite high). The generated output PDF file contains 90deg anticlockwise rotated pages. However, the inverted height-width ratio is the same as the original. So, the pages are only rotated after generation.

Consideration: During a print, I have ticked the 'Choose paper source by PDF size' option.
 
Kindly address the said issue.

Thanks

**Comment by stchan** [comment]
I'm extremely busy right now and haven't done anything with PdfScribe in a while - however, the first priority when I do come back around is to integrate a new port monitor (issue #17)

**Comment by KushX** [comment]
Is there a manual/quick fix/code snippet for this issue? 
Any suggestions would help. I'm not very good at coding, but I have managed to build from the source. But no idea how I'd force it to rotate back to the correct way.

**Comment by stchan** [comment]
If you want to try making changes, lines 68-70 in "Program.cs" sets ghostscript parameters:

```
String[] ghostScriptArguments = { "-dBATCH", "-dNOPAUSE", "-dSAFER",  "-sDEVICE=pdfwrite",
                                                String.Format("-sOutputFile={0}", outputFilename), standardInputFilename,
                                                "-c", @"[/Creator(PdfScribe " + Assembly.GetExecutingAssembly().GetName().Version + " (PSCRIPT5)) /DOCINFO pdfmark", "-f"};
```

**Comment by stchan** [comment]
[Prerelease v1.3.1](https://github.com/stchan/PdfScribe/releases/tag/v1.3.1_prerelease) turns off auto rotation (default is /PageByPage)
