### ISSUE TITLE
Not able to Print Secured Pdf but allowed print

### ISSUE THREAD

**Issue by trilok54660** [stchan/PdfScribe#33]
![image](https://user-images.githubusercontent.com/15190758/79220605-eb29a280-7e71-11ea-8cea-e5afac9d277b.png)
First of all. great project. using sense 2years. I have one pdf which is password protected and i am able to open it without password but its not working with pdfscribe. and that pdf if allowed to Print but its not working. Please help

**Comment by trilok54660** [comment]
this issue occures only in ADOBE READER. please help

**Comment by stchan** [comment]
This is same as issue #25 - like I mentioned earlier, it's no surprise that an Adobe product would refuse to help defeat encryption, and a third party reader would. I'd look into the stackoverflow link posted in #25 if you're interested in researching a solution for your own code.

I'm extremely busy right now and haven't done anything with PdfScribe in a while - however, the first priority when I do come back around is to integrate a new port monitor (issue #17). While I will leave this open, it's highly unlikely I'll address this any time soon.

**Comment by stchan** [comment]
[Pre-release v1.2.1](https://github.com/stchan/PdfScribe/releases/tag/v1.2.1_prerelease) has a fix for this you can try. Set "StripNoRedistill" to "True" in the config file to activate it.

**Comment by stchan** [comment]
fixed in v1.3.0
