### ISSUE TITLE
Printer Not Run Port When Print 

### ISSUE THREAD

**Issue by chuongmep** [stchan/PdfScribe#34]
Dear Stchan ,
When i print PDF, it not starting with services Print Spooler, how to we can fix problem this in windows 10, if you have any solution or any suggest for me , please help, thank you.I have try with PDF24 and PDF Creator, it working normal.
Image describe : 
If i fix by step use troubleshoot, it worked

![image](https://user-images.githubusercontent.com/31106432/101858874-18fbee00-3b9d-11eb-982a-61f6cfba5f8e.png)
Port Working 
![image](https://user-images.githubusercontent.com/31106432/101858844-02559700-3b9d-11eb-8508-bf6ad6c5218e.png)
With start  first computer, it not working and can't seach port to print.

**Comment by stchan** [comment]
v1.0.9 changed some printer defaults - it might possibly help with your issue

**Comment by chuongmep** [comment]
Thanks stchan.
