### ISSUE TITLE
Opening Custom Windows Form

### ISSUE THREAD

**Issue by alijezzini** [stchan/PdfScribe#39]
I created a custom windows form and triggered it using `Application.Run(CustomForm());` from Program.cs in PdfScribe.
When printing a document the form is not showing, but the process keeps running in the background. Any hints why the form not showing up ?

**Comment by sowri1** [comment]
Same issue. I tried creating new form instance and tried `form.ShowDialog()` and `form.Show()`. The form doesn't show up. However, when I tried double clicking the exe, the form showed up. It doesn't show up only when I try to print from some other application.
