### ISSUE TITLE
Option to open PDF after it was created

### ISSUE THREAD

**Issue by da-anda** [stchan/PdfScribe#4]
Thanks for this bloat free nice and simple PDF printer driver. It's exactly what I was looking for. The only thing I miss is an option to automatically open the PDF once it's been written. Would you be able to add this?

side note: the driver is able to print other page sizes than letter (which is stated in your readme here on Github). I at least have no issues with printing documents in the German A4 size correctly.

**Comment by stchan** [comment]
I'll put it on the wishlist, though no promises that I'll do it right away.

And yes, you are correct that it will print to paper sizes other than US Letter - what the readme should say is allow more choices than the default - I'll correct the text.

Glad to hear you found the project useful.

**Comment by stchan** [comment]
in v1.0.6

**Comment by da-anda** [comment]
awesome, thanks a lot
