### ISSUE TITLE
Could not find redmon64pdfscribe.dll source code

### ISSUE THREAD

**Issue by gragonskies** [stchan/PdfScribe#43]
I can not find redmon64pdfscirbe.dll source code. please, how to get it ?

**Comment by stchan** [comment]
It's just the redmon 1.9 dll renamed, with some changes made by a few people who worked on issue #17 (the current DLL was built by @mca0815).

There's a github repo of Redmon [here](https://github.com/ARLM-Keller/redmon) , or you could download it from [ghostgum](http://www.ghostgum.com.au/software/redmon.htm).

That source does not include the changes made by @tahoop, and @mca0815 - you'll have to add them youself. The build process is detailed in this [comment](https://github.com/stchan/PdfScribe/issues/17#issuecomment-830505087).

**Comment by stchan** [comment]
UPDATE: The source for redmon64pdfscribe is now included as a submodule reference.
