### ISSUE TITLE
slient installation 

### ISSUE THREAD

**Issue by ericdai** [stchan/PdfScribe#45]
dot not want wix install ，just exe file to install pdfscribe sothat we can bulk install 100 PC

**Comment by stchan** [comment]
The standard msiexec switches will install PdfScribe silently. The current release could be silently installed with the following command from an elevated (administrator) prompt:

`msiexec /i PdfScribeInstall_1.1.3.0.msi /QN`

There is no supported install method without the MSI. If you don't want to use it, you'll have to write your own scripts to take care of everything the installer does.
