### ISSUE TITLE
Unable to build PdfScribeInstall

### ISSUE THREAD

**Issue by serdor2** [stchan/PdfScribe#47]
When I try to build the solution, I don't understand how to build PdfScribeInstall to get final installer file. After building the PdfScribeInstall\bin\Debug  folder is empty, and I get the following message in the Output:
Skipped Build: Project: PdfScribeInstall, Configuration: Debug x64 ------
3>Project not selected to build for this solution configuration 

Thanks in advance.

**Comment by tisquip** [comment]
Hi @serdor2 , hope you are well. Did you figure out how to build the PdfScribeInstall. I have been at it for quite some time now. Your help will be much appreciated
