### ISSUE TITLE
build failed  wix 3.14 vs 2022

### ISSUE THREAD

**Issue by ericdai** [stchan/PdfScribe#51]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		命令“powershell -command "del ((Split-Path 'E:\PdfScribe-master\PdfScribeInstall\bin\x64\Release\en-us\PdfScribeInstall_1.3.2.31825.msi' -parent) + '\*.sha512')"”已退出，代码为 1。	PdfScribeInstall	C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix.targets	781

**Comment by stchan** [comment]
I can't read that error message (don't know the language), but I'm pretty sure this is a local environment specific issue. I had the solution build with Wix 3.14.1 in two separate environments. You may want to check if your Votive extension is installed properly.

Going forward, there will be no fixes for any future Wix 3.xx issues - 3.xx is end of life, any changes to the installer will be targeting Wix 4+
