### ISSUE TITLE
AddPrinter caused Wins32 error code 1796

### ISSUE THREAD

**Issue by bh-ubunye** [stchan/PdfScribe#52]
Hi @stchan, I was faced the error when trying to add printer. I did lots of googling, but nothing helps my issue.

I couldn't know what the cause is, whether you have any suggestion on this?

**Comment by stchan** [comment]
Couldn't say - only thing I can think of at the moment is generate an install log (use msiexec with the /l*v option) and see if that provides any clues.

**Comment by bh-ubunye** [comment]
these was what I can found.

Info | Port monitor successfully installed.
Info | Printer drivers copied or already exist.
Info | Redirection port added.
Info | Printer driver installed.
Error | Printer driver file was not copied. Exception message: Could not add PDF Scribe virtual printer. Win32 error code 1796.
Error | Could not add printer.

**Comment by bh-ubunye** [comment]
Hi @stchan, May I know that PdfScribe only working with .Net Framework 4.8? does it able to work with .Net 8?

**Comment by stchan** [comment]
.NET Framework (4.8) and .NET 8.0 are not compatible. You'll have to perform a 4.8 --> 8.0 project upgrade (there are tools to do this), then fix any breaking changes if you want to build an 8.0 assembly.

Looks like the README could use an update as it was written long before .NET Core was around.

**Comment by stchan** [comment]
I've applied the "help wanted" label, and will leave this open in case anybody can help.

**Comment by bh-ubunye** [comment]
> .NET Framework (4.8) and .NET 8.0 are not compatible. You'll have to perform a 4.8 --> 8.0 project upgrade (there are tools to do this), then fix any breaking changes if you want to build an 8.0 assembly.
> 
> Looks like the README could use an update as it was written long before .NET Core was around.

Hi @stchan, I did modify the PdfScribe project into .Net 8.0 and my the other .Net 8.0 project referred it but still have same issue. I not sure whether issue related to permission, but I did run it as administrator access.

**Comment by stchan** [comment]
Creating a public fork, and making your work visible would probably increase the chances of finding people who can help.

**Comment by bh-ubunye** [comment]
I found the exact issue causing me to be unable to perform AddPrinter() and error. 

The printer port was not installed correctly, but the return code result is still giving me 0. That's why I keep thinking it was successfully added until I have a detail check for each of the functions and find out it.

Any reason causing the port not to be added correctly? I ensured I granted necessary permission.

**Comment by bh-ubunye** [comment]
Issue resolved. 

I changed the portName.EndWith(string) to portName.EndWith(char), then it resolved in my .Net 8.0 project.

**Comment by Neustradamus** [comment]
@bh-ubunye: Maybe it is possible to have a feature to select if it is .Net Framework 4.8 or .Net 8.0?
