### ISSUE TITLE
Expose paper size to select on printer properties

### ISSUE THREAD

**Issue by thieuquangcuong** [stchan/PdfScribe#6]
I'm looking for a way to make some custom paper size that user can select on printer properties like another printer does. Is there anyway I can make it true? Thanks for spending time for my question!

**Comment by stchan** [comment]
Multiple paper sizes is on my to do list - however, if you want forge ahead, Ghostscript has the -sPAPERSIZE parameter for well known paper types. 

Look at this line in the Program static class (Program.cs):

````
String[] ghostScriptArguments = { "-dBATCH", "-dNOPAUSE", "-dSAFER",  "-sDEVICE=pdfwrite", String.Format("-sOutputFile={0}", outputFilename), standardInputFilename };
````
Make your parameter changes there if you want a quick and dirty fix.

You can read more about Ghostscript paper sizes here:
https://www.ghostscript.com/doc/9.22/Use.htm#Known_paper_sizes

**Comment by stchan** [comment]
closing this as it's already on the to-do list.
