### ISSUE TITLE
AddPrinterDriver caused an win32 error with code 216

### ISSUE THREAD

**Issue by kisskumam** [stchan/PdfScribe#8]
Hi @stchan, thank you for all your idea and hard work on this project. This was helped me to build my own printer. I'm not quite familiar on windows driver code. Therefore, this project costs me a lot of efforts.
Due to unsupported of Wix to build 2 platforms support msi package, then I decided to create 1 package for each platform. The one for 64-bits processor worked perfectly, but for the 32-bits one. I'm facing an win32 error with the code 216. But, with the same 32-bit package, I was able to installed on another computer of my friend.

> win32 - error code 216: The image file %1 is valid, but is for a machine type other than the current machine.  ERROR_EXE_MACHINE_TYPE_MISMATCH

Then I create a program (not an installer) try to create PrinterDriver only with the same function you already provided (level 6 with DRIVER_INFO_6) by calling AddPrinterDriver from winspool.drv. Unfortunately, the error's still happening. 
I have searched for 3 days but it seems no clue for me to resolve this issue. Please give me a help. 

Thank you so much!

**Comment by cuongthieu** [comment]
I have successfully installed on a computer running windows 7 utimate 32-bits. But, that the only one 32-bits machine that I can install. Other computer always returns 216.
Thought it was a registry problem. 
Is there any way else I can manually add the printer driver?

**Comment by kisskumam** [comment]
Thanks for your response. 
I'm not sure whether is it a 32 vs 64-bits problem. Because, there are one computer that is running windows 7 32-bits can be successfully installed. All the other one which is 32-bits (included windows 7,8,10) always return 216 error code.
Thought it can be a problem with computer's registry.
I'm looking for someway that can manually install the driver. Is it possible?

**Comment by stchan** [comment]
No problem - when you fix the problem, please come back and post a comment so that others in the future will be able to read about it.

**Comment by stchan** [comment]
Closing this as the issue was with forked code, rather than the current development trunk.
