### ISSUE TITLE
windows 10 no pdf generated.

### ISSUE THREAD

**Issue by itc-arsalan** [stchan/PdfScribe#9]
Hi,

I was wondering if pdfscribe driver has been tested with windows 10? The driver works fine in Windows 7 but on Windows 10, the pdf output file is not generated. When I look in the event viewer there is an entry:

Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: PdfScribe.exe
P2: 1.0.6621.5424
P3: 5a868fb0
P4: System.Windows.Forms
P5: 4.7.3221.0
P6: 5b885a5a
P7: ad6
P8: 20
P9: System.InvalidOperationException
P10:

**Comment by stchan** [comment]
I just used it a few hours ago on my Win 10 machine (build 1809), and there
haven't been any other reports of Windows 10 specific issues (though I do
not know if people are using it much on Win 10, since it has a built in PDF
printer). Did it generate any other event log entries?

**Comment by itc-arsalan** [comment]
I tried it on Windows 10 Home (build 1803). I will try to find another pc with Windows Pro and try it and let you know. I am guessing that the error is generated in the unmanaged code. I did not see any errors in the UI. 
Thanks.

**Comment by itc-arsalan** [comment]
I did some debugging and it is failing on line 94 of Program.cs.
```
if (instance == "" || instance == ":instance1")
                        {

                            string printer1 = Path.Combine(specificFolder, "scribe");
                            **doc = System.Xml.Linq.XDocument.Load(@printer1 + "\\" + "config.xml");**
                        }
```
It is looking for config.xml at the path:
c:\windows\system32\config\systemprofile\AppData\Roaming\PdsScribe\Scribe

which does not exist. The same folder does not exist on my Windows 7 but I do not get any errors using the same msi installer.

**Comment by itc-arsalan** [comment]
I am using PdfScribe 1.0.5.

**Comment by stchan** [comment]
There weren't many changes between 1.0.5 and 1.0.6 - and that code fragment does not seem familiar at all. PdfScribe does not keep any user scoped settings - they're all application scoped. Line 94 writes a trace event. Was your installer built from source, or was it downloaded from the releases page? Also is there any particular reason why you're using 1.0.5 instead of the current 1.0.6?

**Comment by itc-arsalan** [comment]
I am not sure if you are looking at the same as I am. I am looking at Line 94 from the PdfScribe project in the Program.cs file. This code is trying to load config.xml from the USERPROFILE environment variable. 

```
string folder = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
                        string specificFolder = Path.Combine(folder, "PdfScribe");
                        System.Xml.Linq.XDocument doc = new System.Xml.Linq.XDocument();
                        //MessageBox.Show("Instance = " + instance);
                        if (instance == "" || instance == ":instance1")
                        {

                            string printer1 = Path.Combine(specificFolder, "scribe");
                            doc = System.Xml.Linq.XDocument.Load(@printer1 + "\\" + "config.xml");
                        }
```

I tried using both, bulding my installer from source and using the one provided on the release page.

The reason I am using 1.0.5 is because I have visual studio 2015, and 1.0.6 mentions specifically that it needs Visual studio 2017 with its corresponding wix extension.

**Comment by stchan** [comment]
Yes, I'm looking at  Program.cs in PdfScribe - this is in the GetOutputFilename() function. correct? That doesn't look like my code - could you possibly be looking at a fork of my project?

**Comment by itc-arsalan** [comment]
Sorry looks like I was working off this fork 

https://github.com/Libki/PdfScribe

**Comment by jthou** [comment]
In fact, this fork has the same issue. I tried it a whole day on Win10, but it does not work. and I just see your issue reporting here. And tried on Win7, it works fine.

**Comment by jthou** [comment]
After did some tracing, I found that none of the dialogs can be shown, no matter the MessageBox, or SaveFileDialog, etc.

**Comment by stchan** [comment]
I haven't been able to reproduce this on two different Windows 10 installs (both 1809). Open a new issue, post any relevant information, and hopefully others who have the issue will chime in and there will be enough information to solve the problem.
